name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

profile: 'jaffle_shop'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:    # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
  jaffle_shop:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      +static_analysis: strict
      +labels:
        layer: staging
        managed_by: dbt_dev

    marts:
      +enabled: true
      +materialized: table
      +static_analysis: strict
      +labels:
        layer: marts
        managed_by: dbt_dev

    python_demo:    # takes over 20 minutes of startup time to run so we disable it by default
      +enabled: false

seeds:
  +enabled: false

analyses:
  +enabled: true

flags:
  require_generic_test_arguments_property: true