jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-dev-503215
      dataset: dbt_dev
      keyfile: .bq_service_accounts/dev-dbt-dev-503215-67bb437f0a37.json
      threads: 4
      location: US  # <--- ADD THIS LINE (Must match your dataset location)

    prod:
      type: bigquery
      method: service-account
      project: dbt-prod-503215
      dataset: dbt_prod
      keyfile: .bq_service_accounts/prod-dbt-dev-503215-530c71042271.json
      threads: 8
      location: US 

# default:
#   target: dev
#   outputs:
#     dev:
#       type: bigquery
#       threads: 16
#       database: dbt-dev-503215
#       schema: dbt_dev
#       method: service-account
#       keyfile: /home/serge/projects/dbt_fundamentals/.bq_service_accounts/dev-dbt-dev-503215-67bb437f0a37.json
#       location: us-east1
#       dataproc_batch: null
