version: 2

sources:
  - name: jaffle_shop
    description: "Raw data from the Jaffle Shop application"
    database: raw-data-503215   # The Project ID
    schema: jaffle_shop         # The Dataset name
    tables:
      - name: customers
        description: "One row per customer"
      - name: orders
        description: "One row per order"


  - name: stripe
    description: "Raw data from the Stripe payment processor"
    database: raw-data-503215   # The Project ID
    schema: stripe         # The Dataset name
    tables:
      - name: payment
        description: "One row per payment"